#!/bin/sh
set -e


# create a user to run as
if [ "$1" = "configure" ]; then
  adduser --system  --home /run/midiminder --gecos "midiminder daemon" \
          --no-create-home --disabled-password --ingroup audio \
          --quiet midiminder || true

fi

#DEBHELPER#
